name: Test Compiler

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_FLAGS="-g -O0"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Enable Core Dumps
      run: ulimit -c unlimited

    - name: Run Tests
      run: |
        ctest --test-dir ${{github.workspace}}/build --output-on-failure -C ${{env.BUILD_TYPE}}
        if [ -f core ]; then
          gdb -c core ${{github.workspace}}/build/tiny_optimizing_compiler -ex "bt" -ex "q"
        fi
