name: Test Compiler

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup C++ Environment
        uses: actions/setup-cpp@v3
        with:
          cmake-version: '3.28.x'

      - name: Build Compiler
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run Tiny Samples
        run: |
          for file in samples/*.tiny; do
            ./build/tiny_optimizing_compiler "$file"
          done
